#!/bin/sh
#

PORT=$(grep "^http_port=" /etc/default/config | cut -d = -f 2)
PARAM="-c /etc/httpd.conf -h /usr/share/www"
KIND="HTTPD"
HOSTNAME=$(grep "^hostname=" /etc/default/config | cut -d = -f 2)

start() {
	echo "Starting $KIND service..."
    start-stop-daemon -S -q --exec httpd -- ${PARAM} -p ${PORT} -r ${HOSTNAME}
    echo $! > /var/run/httpd.pid
}

stop() {
	echo "Shutting down $KIND service..."
	start-stop-daemon -K -q -n httpd
    echo "OK"
}

restart() {
	stop
	sleep 1
	start
}	

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart)
  	restart
	;;
  reload)
  	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart|reload}"
	exit 1
esac

